// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type CreateProjectReq struct {
	OrgID        int64  `json:"orgId"`
	Code         string `json:"code"`
	Name         string `json:"name"`
	PreCode      string `json:"preCode"`
	Owner        int64  `json:"owner"`
	Type         int    `json:"type"`
	PriorityID   int64  `json:"priorityId"`
	PublicStatus int    `json:"publicStatus"`
	ResourceID   int64  `json:"resourceId"`
	Remark       string `json:"remark"`
	Status       int    `json:"status"`
}

type DeleteProjectReq struct {
	ID int64 `json:"id"`
}

type JsAPISignReq struct {
	Type   string `json:"type"`
	URL    string `json:"url"`
	CorpID string `json:"corpId"`
}

type JsAPISignResp struct {
	AgentID   int    `json:"agentId"`
	TimeStamp string `json:"timeStamp"`
	NoceStr   string `json:"noceStr"`
	Signature string `json:"signature"`
}

type Project struct {
	ID           int64     `json:"id"`
	OrgID        int64     `json:"orgId"`
	Code         string    `json:"code"`
	Name         string    `json:"name"`
	PreCode      string    `json:"preCode"`
	Owner        int64     `json:"owner"`
	Type         int       `json:"type"`
	PriorityID   int64     `json:"priorityId"`
	PublicStatus int       `json:"publicStatus"`
	ResourceID   int64     `json:"resourceId"`
	Remark       string    `json:"remark"`
	Status       int       `json:"status"`
	Creator      int64     `json:"creator"`
	CreateTime   time.Time `json:"createTime"`
	Updator      int64     `json:"updator"`
	UpdateTime   time.Time `json:"updateTime"`
	Bersion      int       `json:"bersion"`
	IsDelete     int       `json:"isDelete"`
}

type UpdateProjectReq struct {
	ID           int64   `json:"id"`
	OrgID        *int64  `json:"orgId"`
	Code         *string `json:"code"`
	Name         *string `json:"name"`
	PreCode      *string `json:"preCode"`
	Owner        *int64  `json:"owner"`
	Type         *int    `json:"type"`
	PriorityID   *int64  `json:"priorityId"`
	PublicStatus *int    `json:"publicStatus"`
	ResourceID   *int64  `json:"resourceId"`
	Remark       *string `json:"remark"`
	Status       *int    `json:"status"`
}

type User struct {
	Name *string `json:"name"`
}
